DROP TABLE IF EXISTS MEMBER; -- 유저 정보
DROP TABLE IF EXISTS VACATION_INFO; -- 휴가 정보

-- 유저 및 휴가관리 테이블 생성
CREATE TABLE MEMBER (ID VARCHAR(20) PRIMARY KEY, NAME VARCHAR(20), PASSWORD VARCHAR(50), ANNUAL DECIMAL(5, 2), AUNNUAL_USE DECIMAL(3, 2), CRET_DT DATE);
CREATE TABLE VACATION_INFO (ID VARCHAR(20) PRIMARY KEY,VACATION_TYPE CHAR(1), VACATION_ST_DATE DATE, VARCATION_END_DATE DATE);

-- 로그인을 위한 유저 데이터 추가
INSERT INTO MEMBER (ID, NAME, PASSWORD, ANNUAL, AUNNUAL_USE, CRET_DT) VALUES ('test', '테스터', 'test', 15, 0, CURRENT_DATE);